{{config(materialized = 'table')}}

SELECT COMPANY_NAME, COUNT(DISTINCT(EXPERIENCE_LEVEL)) AS TOTAL_LEVELS,
COUNT(*) AS TOTAL_JOBS
FROM {{ref('int_data_roles')}}
GROUP BY COMPANY_NAME
HAVING COUNT(DISTINCT(EXPERIENCE_LEVEL)) > 1
ORDER BY TOTAL_LEVELS DESC
LIMIT 20
